<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.10" />
    <PackageReference Include="TUnit" Version="1.63.25" />
    <ProjectReference Include="..\..\src\Demo.Shared\Demo.Shared.csproj" />
  </ItemGroup>
</Project>
