<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>    
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Nuke.Common" Version="10.1.0" />
    <PackageReference Include="NuGet.Packaging" Version="7.6.0" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>CP.Nuke.BuildTools.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
